config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:omniauth_callbacks => 'users/omniauth_callbacks'}
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"

  devise_scope :user do
    resources :vat_codes
    get 'vat_codes/poll', to: 'vat_codes#poll', as: 'vat_codes_poll'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/integration.rb
class Integration < ApplicationRecord
  self.primary_key = 'uuid'
  
  belongs_to :user
  has_many :vat_codes
  enum integration_type: { exact_online: 0, salesforce: 1 }
end

app/models/user.rb
class User < ApplicationRecord

  has_many :integrations

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable

  def add_integration(auth)
    self.integrations.where(integration_type: auth.provider).first_or_initialize.tap do |integration|
      integration.integration_type = auth.provider
      integration.uid = auth.uid
      integration.name = auth.info.name
      integration.email = auth.info.email
      integration.language = auth.extra.language
      integration.org_id = auth.info.division
      integration.locale = ''
      integration.timezone = ''
      integration.oauth_token = auth.credentials.token
      integration.refresh_token = auth.credentials.refresh_token
      integration.expires_at = auth.credentials.expires_at
      integration.save!
    end
  end
end

app/models/vat_code.rb
class VatCode < ApplicationRecord

  belongs_to :integration
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!, only: :index
  def index
    puts "Home working"
  end
end

app/controllers/integrations_controller.rb
class IntegrationsController < ApplicationController
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  def exact_online
    auth = request.env['omniauth.auth']
    # puts "Auth data: #{auth.to_yaml}"

    current_user.add_integration(auth)
    redirect_to root_path, notice: "Successfully connected to Exact Online"
  end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  def failure
    # puts "Session State: #{session['omniauth.state']}"
    redirect_to root_path, alert: 'Authentication failed'
  end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/vat_codes_controller.rb
class VatCodesController < ApplicationController
  before_action :set_vat_code, only: %i[ show edit update destroy ]

  # GET /vat_codes or /vat_codes.json
  def index
    @vat_codes = VatCode.all
  end

  # GET /vat_codes/1 or /vat_codes/1.json
  def show
  end

  # GET /vat_codes/new
  def new
    @vat_code = VatCode.new
  end

  # GET /vat_codes/1/edit
  def edit
  end

  # POST /vat_codes or /vat_codes.json
  def create
    @vat_code = VatCode.new(vat_code_params)

    respond_to do |format|
      if @vat_code.save
        format.html { redirect_to vat_code_url(@vat_code), notice: "Vat code was successfully created." }
        format.json { render :show, status: :created, location: @vat_code }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @vat_code.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vat_codes/1 or /vat_codes/1.json
  def update
    respond_to do |format|
      if @vat_code.update(vat_code_params)
        format.html { redirect_to vat_code_url(@vat_code), notice: "Vat code was successfully updated." }
        format.json { render :show, status: :ok, location: @vat_code }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @vat_code.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vat_codes/1 or /vat_codes/1.json
  def destroy
    @vat_code.destroy!

    respond_to do |format|
      format.html { redirect_to vat_codes_url, notice: "Vat code was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  # poll to perform the job that gets the current set of all vat codes
  def poll
    # VatCodePollJob.perform_later
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vat_code
      @vat_code = VatCode.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def vat_code_params
      params.require(:vat_code).permit(:guid, :gl_to_pay, :description, :code, :account_code, :account)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/integrations_helper.rb
module IntegrationsHelper
end

app/helpers/vat_codes_helper.rb
module VatCodesHelper
end

app/views/home/index.html.erb
<h1>This is a home page</h1>

app/views/layouts/_nav.html.erb
<nav>
    <ul>
        <% if user_signed_in? %>
            <li><%= link_to 'Edit your account', edit_user_registration_path %></li>
            <li><%= button_to "Connect Exact Online", user_exact_online_omniauth_authorize_path, form: {target: '_blank'} %></li>
            <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete,  data: { turbo_method: :delete } %></li>
        <% else %>
            <li><%= link_to 'Sign in', new_user_session_path %></li>
            <li><%= link_to 'Sign up', new_user_registration_path %></li>
        <%end %>
    </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsExactOnline</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/nav'%>
    
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/vat_codes/_form.html.erb
<%= form_with(model: vat_code) do |form| %>
  <% if vat_code.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(vat_code.errors.count, "error") %> prohibited this vat_code from being saved:</h2>

      <ul>
        <% vat_code.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :guid, style: "display: block" %>
    <%= form.text_field :guid %>
  </div>

  <div>
    <%= form.label :gl_to_pay, style: "display: block" %>
    <%= form.text_field :gl_to_pay %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :code, style: "display: block" %>
    <%= form.text_field :code %>
  </div>

  <div>
    <%= form.label :account_code, style: "display: block" %>
    <%= form.text_field :account_code %>
  </div>

  <div>
    <%= form.label :account, style: "display: block" %>
    <%= form.text_field :account %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/vat_codes/_vat_code.html.erb
<div id="<%= dom_id vat_code %>">
  <p>
    <strong>Guid:</strong>
    <%= vat_code.guid %>
  </p>

  <p>
    <strong>Gl to pay:</strong>
    <%= vat_code.gl_to_pay %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= vat_code.description %>
  </p>

  <p>
    <strong>Code:</strong>
    <%= vat_code.code %>
  </p>

  <p>
    <strong>Account code:</strong>
    <%= vat_code.account_code %>
  </p>

  <p>
    <strong>Account:</strong>
    <%= vat_code.account %>
  </p>

</div>

app/views/vat_codes/edit.html.erb
<h1>Editing vat code</h1>

<%= render "form", vat_code: @vat_code %>

<br>

<div>
  <%= link_to "Show this vat code", @vat_code %> |
  <%= link_to "Back to vat codes", vat_codes_path %>
</div>

app/views/vat_codes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Vat codes</h1>

<div id="vat_codes">
  <% @vat_codes.each do |vat_code| %>
    <%= render vat_code %>
    <p>
      <%= link_to "Show this vat code", vat_code %>
    </p>
  <% end %>
</div>

<%= link_to vat_codes_poll_path() do %>
  <p type="button">Refresh</p>
<% end %>

<%= link_to "New vat code", new_vat_code_path %>

app/views/vat_codes/new.html.erb
<h1>New vat code</h1>

<%= render "form", vat_code: @vat_code %>

<br>

<div>
  <%= link_to "Back to vat codes", vat_codes_path %>
</div>

app/views/vat_codes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @vat_code %>

<div>
  <%= link_to "Edit this vat code", edit_vat_code_path(@vat_code) %> |
  <%= link_to "Back to vat codes", vat_codes_path %>

  <%= button_to "Destroy this vat code", @vat_code, method: :delete %>
</div>